exports.Schema = mongoose.Schema(
		{
			_id:'number',
			token:'string',
			tokenSecret:'string',
			friends:'array',
			uninvited_friends:[{
				screen_name:'string',
				id:'string',
				profile_image_url:'string',
				invited:'boolean'
			}],
			request_friends:[{
				screen_name:'string',
				id:'string',
				profile_image_url:'string'
			}],
			friendships:[{
				screen_name:'string',
				id:'string',
				profile_image_url:'string'
			}],
			last_sync:'date',
			username:"string",
			raw:{},
			screen_name:"string", 
			profile_image_url:"string"
		},
		{
			strict:false
		}
	);

